#--------------- config file -----------------#

# video path
video_path: D:\Pycharm_Projects\qu_holmes_su_release\tests\qudashen.mp4
#video_path: Z:\dataset\qususu\0923\easyflytracker_test\202009231045.avi
# 输出文件夹
#output_dir: Z:\dataset\qususu\0923\easyflytracker_test\output
output_dir: D:\Pycharm_Projects\qu_holmes_su_release\tests\output
# begin calculate time point, (minute)
begin_time: 0
# how long time to calculate, (minute)，可以设为None或者0，到视频结束停止
duration_time: None
# show track result, True or False
show_track_result: False
#, True or False
skip_config: False


############### analysis ########################
# config roi path, search in the video_path directory if None
group_path: D:\Pycharm_Projects\qu_holmes_su_release\tests\output\grop.xlsx
# 内圈面积阈值
area_th: 0.5
# 分析移动距离的时候每个值需要统计的时间跨度（单位：分钟）
ana_time_duration: 0.5
# 统计睡眠信息的时候每个值需要统计的时间跨度（单位：分钟）
sleep_time_duration: 1
#dish_radius_mm: 10
# AB两点的距离，单位毫米
AB_dist_mm: 120
# 去畸变参数路径，设为None则不使用去畸变功能，否则就设置正确的模型路径
Undistortion_model_path: None
############### analysis ########################



################ Camera Calibration #################
# 已拍摄的标记图像所在文件夹
calibration_images_files_dir: D:\Pycharm_Projects\qu_holmes_su_release\imgs\camera_calibration\traindatas

# 标记模型保存结果
calibration_model_saved_dir: D:\Pycharm_Projects\qu_holmes_su_release\imgs\camera_calibration\model

# 棋盘大小
chess_size: [6, 9]

################ Camera Calibration #################