# config file

# video path
video_path: D:\Pycharm_Projects\qu_holmes_su_release\tests\demo.mp4
# begin calculate time point, (minute)
begin_time: 0
# how long time to calculate, (minute)
duration_time: 2
# show track result
show_track_result: False

# config roi path, search in the video_path directory if None
config_roi:
#
area_th: 0.5
#
ana_time_duration: 0.5
#
dish_radius_mm: 10
